#!/bin/bash
set -euo pipefail

apt-get install -y gnupg curl

curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | \
  gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg --dearmor

echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" \
  > /etc/apt/sources.list.d/mongodb-org-6.0.list

apt-get update
apt-get install -y mongodb-org

systemctl daemon-reload
systemctl enable mongod
systemctl start mongod
systemctl --no-pager --full status mongod